# all:
#   sf_gwo_plugin:
#     enabled:      off
#     uacct:        XX-XXXXX-X
#     classes:
#       ab:         sfGWOExperimentAB
#       multi:      sfGWOExperimentMulti
#     experiments:
#       # the following represents an example A/B experiment, not default values
#       home_page1:
#         enabled:  on
#         type:     ab
#         uacct:    XX-XXXXX-X
#         key:      0000000000
#         pages:
#           original: { module: main, action: index }
#           variations:
#             - { module: main, action: index2 }
#             - { module: main, action: index3 }
#           conversion: { module: sfGuardAuth, action: register }
